version: "3.7"

services:
  site:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: project_web
    volumes:
      - ./datadir:/var/lib/mysql
  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
